consumer_key = "YOUR_CONSUMER_KEY"
consumer_secret = "YOUR_CONSUMER_SECRET"
access_token = "YOUR_ACCESS_TOKEN"
access_token_secret = "YOUR_ACCESS_TOKEN_SECRET"
bot_token = "YOUR_TELEGRAM_BOT_TOKEN"
api_id = "your api id get it from https://my.telegram.org/apps"
api_hash = "your api hash get it from https://my.telegram.org/apps"
